### ISSUE TITLE
docker 运行报错

### ISSUE THREAD

**Issue by Z-fly** [iSafeBlue/TrackRay#31]
root@714d2878e6b6:~/trackray-framework/release# java -jar trackray.jar
03:40:48.333 [main] INFO com.trackray.base.utils.PropertyUtil - 开始加载properties文件内容.......
03:40:48.336 [main] INFO com.trackray.base.utils.PropertyUtil - 加载properties文件内容完成...........
当前插件加载目录:/root/trackray-framework/release/resources/plugin

 _______             _    _____
|__   __|           | |  |  __ \
   | |_ __ __ _  ___| | _| |__) |__ _ _   _
   | | '__/ _` |/ __| |/ /  _  // _` | | | |
   | | | | (_| | (__|    | | \ \ (_| | |_| |
   |_|_|  \__,_|\___|_|\_\_|  \_\__,_|\__, |
                                       __/ |
                                      |___/     [v3.2.1]

使用 --help 参数查看更多帮助
2020-09-25 03:40:48.718  INFO 2146 --- [           main] com.trackray.WebApplication              : Starting WebApplication v3.2.1 on 714d2878e6b6 with PID 2146 (/root/trackray-framework/release/trackray.jar started by root in /root/trackray-framework/release)
2020-09-25 03:40:48.719  INFO 2146 --- [           main] com.trackray.WebApplication              : No active profile set, falling back to default profiles: default
2020-09-25 03:40:49.621  INFO 2146 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-09-25 03:40:49.715  INFO 2146 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 86ms. Found 7 repository interfaces.
2020-09-25 03:40:50.082  INFO 2146 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$fdc30a37] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-09-25 03:40:50.494  INFO 2146 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 80 (http)
2020-09-25 03:40:50.521  INFO 2146 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-09-25 03:40:50.521  INFO 2146 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/9.0.13
2020-09-25 03:40:50.531  INFO 2146 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
2020-09-25 03:40:50.590  INFO 2146 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-09-25 03:40:50.591  INFO 2146 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1840 ms
2020-09-25 03:40:50.734  INFO 2146 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-09-25 03:40:50.737  WARN 2146 --- [           main] com.zaxxer.hikari.util.DriverDataSource  : Registered driver with driverClassName=org.hsqldb.jdbcDriver was not found, trying direct instantiation.
2020-09-25 03:40:51.030  INFO 2146 --- [           main] hsqldb.db.HSQLDB74C3576A7E.ENGINE        : checkpointClose start
2020-09-25 03:40:51.030  INFO 2146 --- [           main] hsqldb.db.HSQLDB74C3576A7E.ENGINE        : checkpointClose synched
2020-09-25 03:40:51.057  INFO 2146 --- [           main] hsqldb.db.HSQLDB74C3576A7E.ENGINE        : checkpointClose script done
2020-09-25 03:40:51.075  INFO 2146 --- [           main] hsqldb.db.HSQLDB74C3576A7E.ENGINE        : checkpointClose end
2020-09-25 03:40:51.082  INFO 2146 --- [           main] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Driver does not support get/set network timeout for connections. (feature not supported)
2020-09-25 03:40:51.085  INFO 2146 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2020-09-25 03:40:51.138  INFO 2146 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2020-09-25 03:40:51.193  INFO 2146 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
2020-09-25 03:40:51.194  INFO 2146 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2020-09-25 03:40:51.301  INFO 2146 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2020-09-25 03:40:51.453  INFO 2146 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
2020-09-25 03:40:52.105  INFO 2146 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2020-09-25 03:40:52.796  INFO 2146 --- [           main] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2020-09-25 03:40:52.808  INFO 2146 --- [           main] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2020-09-25 03:40:52.808  INFO 2146 --- [           main] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.0 created.
2020-09-25 03:40:52.809  INFO 2146 --- [           main] org.quartz.simpl.RAMJobStore             : RAMJobStore initialized.
2020-09-25 03:40:52.809  INFO 2146 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.0) 'schedulerFactoryBean' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2020-09-25 03:40:52.809  INFO 2146 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'schedulerFactoryBean' initialized from an externally provided properties instance.
2020-09-25 03:40:52.809  INFO 2146 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.0
2020-09-25 03:40:52.810  INFO 2146 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: com.trackray.base.quartz.SpringJobFactory@18463720
2020-09-25 03:40:52.950  INFO 2146 --- [           main] c.t.b.configuration.XRayConfiguration    : [xray] 正在启动xray被动代理 [127.0.0.1:7777]
2020-09-25 03:40:52.951  WARN 2146 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'XRayConfiguration': Unsatisfied dependency expressed through field 'xRayExecutor'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xRayExecutor' defined in class path resource [com/trackray/base/configuration/XRayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.commons.exec.DefaultExecutor]: Circular reference involving containing bean 'XRayConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'initXRay' threw exception; nested exception is java.lang.NullPointerException
2020-09-25 03:40:52.952  INFO 2146 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_NON_CLUSTERED shutting down.
2020-09-25 03:40:52.952  INFO 2146 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_NON_CLUSTERED paused.
2020-09-25 03:40:52.952  INFO 2146 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_NON_CLUSTERED shutdown complete.
2020-09-25 03:40:52.953  INFO 2146 --- [           main] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
2020-09-25 03:40:52.953  INFO 2146 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-09-25 03:40:52.955  INFO 2146 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-09-25 03:40:52.982  INFO 2146 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2020-09-25 03:40:52.985  INFO 2146 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-09-25 03:40:53.002  INFO 2146 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-09-25 03:40:53.008 ERROR 2146 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'XRayConfiguration': Unsatisfied dependency expressed through field 'xRayExecutor'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xRayExecutor' defined in class path resource [com/trackray/base/configuration/XRayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.commons.exec.DefaultExecutor]: Circular reference involving containing bean 'XRayConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'initXRay' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
        at com.trackray.WebApplication.run(WebApplication.java:85) [trackray.jar:3.2.1]
        at com.trackray.WebApplication.main(WebApplication.java:53) [trackray.jar:3.2.1]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xRayExecutor' defined in class path resource [com/trackray/base/configuration/XRayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.commons.exec.DefaultExecutor]: Circular reference involving containing bean 'XRayConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'initXRay' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        ... 20 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.commons.exec.DefaultExecutor]: Circular reference involving containing bean 'XRayConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'initXRay' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        ... 33 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.trackray.base.configuration.XRayConfiguration.initXRay(XRayConfiguration.java:57) ~[base-3.2.1.jar:3.2.1]
        at com.trackray.base.configuration.XRayConfiguration$$EnhancerBySpringCGLIB$$44b1c9ed.CGLIB$initXRay$0(<generated>) ~[base-3.2.1.jar:3.2.1]
        at com.trackray.base.configuration.XRayConfiguration$$EnhancerBySpringCGLIB$$44b1c9ed$$FastClassBySpringCGLIB$$6256d98c.invoke(<generated>) ~[base-3.2.1.jar:3.2.1]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at com.trackray.base.configuration.XRayConfiguration$$EnhancerBySpringCGLIB$$44b1c9ed.initXRay(<generated>) ~[base-3.2.1.jar:3.2.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        ... 34 common frames omitted

root@714d2878e6b6:~/trackray-framework/release#

**Comment by iSafeBlue** [comment]
Linux平台下的bug，换Windows或者参照 #30 

这两天有时间会修复一下

**Comment by Z-fly** [comment]
> Linux平台下的bug，换Windows或者参照 #30
> 
> 这两天有时间会修复一下

Docker用的Debain8太老了，python只能靠apt装3.4。
换成Debain10.5吧

**Comment by Z-fly** [comment]
@iSafeBlue 还有依赖文件能否同时传一份到天翼云上？

**Comment by ZZtac** [comment]
> Linux平台下的bug，换Windows或者参照 #30
> 
> 这两天有时间会修复一下

大佬，以及账号密码修改后，也没有生效，还是默认密码账号

**Comment by ZZtac** [comment]
> Linux平台下的bug，换Windows或者参照 #30
> 
> 这两天有时间会修复一下
还有具体调用哪些接口能说明下吗，比如msf= =

**Comment by Z-fly** [comment]
就是运行 msfrpcd -U msf -P msf -S -f
application.properties 修改

metasploit.host=127.0.0.1:55553
metasploit.user=msf
metasploit.pass=msf

**Comment by ZZtac** [comment]
> 就是运行 msfrpcd -U msf -P msf -S -f
> application.properties 修改
> 
> metasploit.host=127.0.0.1:55553
> metasploit.user=msf
> metasploit.pass=msf

我有点不明白，msf是下载，这个扫描器调用接口，还是自带，包括sqlmap这些

**Comment by Z-fly** [comment]
> > 就是运行 msfrpcd -U msf -P msf -S -f
> > application.properties 修改
> > metasploit.host=127.0.0.1:55553
> > metasploit.user=msf
> > metasploit.pass=msf
> 
> 我有点不明白，msf是下载，这个扫描器调用接口，还是自带，包括sqlmap这些

目前都不自带，docker也没有自带各种工具。要自己手动启动工具
